### ISSUE TITLE
Add support for local storage so that the user can close the tab and open it back, and his work is not lost

### ISSUE THREAD

**Issue by shrn01** [shrn01/code-white#2]
- Use Local Storage to store the data. **Do not use Session Storage**
- Make sure that this operation doesn't make the site unusable for the user.

**Comment by su-mit** [comment]
Hi @shrn01, which data you are referring to being stored? Can you please throw some more light on that, please!

**Comment by shrn01** [comment]
Sure, actually the data that the user types into the input page goes into the page state right now. But when the user closes the tab  and reopens it, this data is lost. 
So we should periodically autosave the current state of the page, I mean the text typed into the local storage, and when the user closes the page and comes back, we need to check if there is data in the page, and if yes we should prepopulate it into the current state.
There are 2 actions here
- We need to save the text periodically to local storage 
- Check if there is any data from previous session when the user reloads the page

Please ask if there are any more doubts

Adding [this](https://www.freecodecamp.org/news/how-to-use-localstorage-with-react-hooks-to-set-and-get-items/) article which provides information on how this can be done

Cheers! 😄

**Comment by su-mit** [comment]
thnx for clarification @shrn01, I will work on this

**Comment by shrn01** [comment]
Ok, will assign it to you

**Comment by shrn01** [comment]
Hey @su-mit are you still working on this?

**Comment by shrn01** [comment]
Added
